name: autoterm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - boto3~=1.24
  - fiona~=1.8
  - geopandas~=0.11
  - gdal~=3.2
  - matplotlib~=3.5
  - numpy~=1.23
  - pandas~=1.4
  - Pillow~=9.1
  - psutil~=5.9
  - pyfftw~=0.13
  - rasterio~=1.2
  - scipy~=1.8
  - Shapely~=1.8
  - jupyterlab~=3.4
  - notebook~=6.1.4
  - conda-lock~=1.0
  - pip
  - geojson
  - pyproj
  - pip:
    - ttictoc
platforms:
  - linux-64
  - osx-64
  - win-64
